### PR TITLE
Added surface area measurement

### PR DESCRIPTION
**Pull request by chum13-985**
1)added a new var named sa stands for sueface area. 
 2)added the formula to measure sa.
Please review my code if any more features need to be added let me know.

### CODE REVIEW

**Comment by tiyasaha** [comment]
ok good its ok but can you please replace x and y with X and Y and sa=2(x+y) format

**Comment by tiyasaha** [comment]
*sa=2(X*Y) format

**Comment by chum13-985** [comment]
okay

**Comment by chum13-985** [comment]
changed the format of sa as desired please check

**Pull request closed without merging**
